In [1]:
import numpy as np
import pandas as pd

In [4]:
df=pd.read_csv(r"d:\Downloads_ML_aaa\play_tennis.csv")
df.drop(columns=["day"],axis=1)

     outlook  temp humidity    wind play
0      Sunny   Hot     High    Weak   No
1      Sunny   Hot     High  Strong   No
2   Overcast   Hot     High    Weak  Yes
3       Rain  Mild     High    Weak  Yes
4       Rain  Cool   Normal    Weak  Yes
5       Rain  Cool   Normal  Strong   No
6   Overcast  Cool   Normal  Strong  Yes
7      Sunny  Mild     High    Weak   No
8      Sunny  Cool   Normal    Weak  Yes
9       Rain  Mild   Normal    Weak  Yes
10     Sunny  Mild   Normal  Strong  Yes
11  Overcast  Mild     High  Strong  Yes
12  Overcast   Hot   Normal    Weak  Yes
13      Rain  Mild     High  Strong   No

In [5]:
df.sample(3)

  day   outlook  temp humidity  wind play
0  D1     Sunny   Hot     High  Weak   No
7  D8     Sunny  Mild     High  Weak   No
2  D3  Overcast   Hot     High  Weak  Yes

In [8]:
df["play"].value_counts()

play
Yes    9
No     5
Name: count, dtype: int64

In [10]:
py=(9/14)
pn=(5/14)

In [11]:
pd.crosstab(df["outlook"],df["play"])

play      No  Yes
outlook
Overcast   0    4
Rain       2    3
Sunny      3    2

In [18]:
pd.crosstab(df["humidity"],df["play"])

play      No  Yes
humidity
High       4    3
Normal     1    6