In [1]:
import numpy as np
import pandas as pd
import seaborn as sns

In [2]:
orders=pd.read_csv(r"d:\Downloads_ML_aaa\orders.csv")
messages=pd.read_csv(r"d:\Downloads_ML_aaa\messages.csv")

In [6]:
orders.head()
# messages.head()

         date  product_id  city_id  orders
0  2019-12-10        5628       25       3
1  2018-08-15        3646       14     157
2  2018-10-23        1859       25       1
3  2019-08-17        7292       25       1
4  2019-01-06        4344       25       3

In [5]:
orders.info()
messages.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 4 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   date        1000 non-null   object
 1   product_id  1000 non-null   int64
 2   city_id     1000 non-null   int64
 3   orders      1000 non-null   int64
dtypes: int64(3), object(1)
memory usage: 31.4+ KB
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   date    1000 non-null   object
 1   msg     1000 non-null   object
dtypes: object(2)
memory usage: 15.8+ KB

## Working With Dates

In [ ]:
orders["date"]=pd.to_datetime(orders["date"]) # converitng col in datetime

In [60]:
# extracting year
orders["date_year"]=orders["date"].dt.year
# extracting month
orders["date_month"]=orders["date"].dt.month
# for month name 
#orders["date_month"]=orders["date"].dt.month_name()
# extracting day
orders["date_day"]=orders["date"].dt.day

# day of week
# orders["Week_day_num"]=orders["date"].dt.day_of_week
orders["week_day"]=orders["date"].dt.day_name()

# weekend or not
orders["weekend"]=np.where(orders["week_day"].isin(["Sunday","Friday","Saturday"]),1,0)

# week number of the year
orders["week_number"]=orders["date"].dt.isocalendar().week

# quarter of year
orders["year_quarter"]=orders["date"].dt.quarter

In [61]:
o=orders["Week_day"].value_counts()
print(o)
# orders.drop(columns=["product_id","city_id"],axis=1,inplace=True)
orders.head()

Week_day
Friday       177
Saturday     156
Wednesday    155
Monday       133
Sunday       128
Thursday     127
Tuesday      124
Name: count, dtype: int64

,date,orders,date_year,date_day,date_month,Week_day,week_day,weekend,week_number,year_quarter
0,2019-12-10,3,2019,10,12,Tuesday,Tuesday,0,50,4
1,2018-08-15,157,2018,15,8,Wednesday,Wednesday,0,33,3
2,2018-10-23,1,2018,23,10,Tuesday,Tuesday,0,43,4
3,2019-08-17,1,2019,17,8,Saturday,Saturday,1,33,3
4,2019-01-06,3,2019,6,1,Sunday,Sunday,1,1,1

In [27]:
orders["date_month"].value_counts()

date_month
11    146
10    129
12    120
8     115
7     111
9      68
6      65
1      58
4      55
3      49
5      42
2      42
Name: count, dtype: int64

## Exact time elapsed btw date

In [64]:
import datetime
date=datetime.datetime.today()
date

datetime.datetime(2026, 8, 27, 12, 45, 18, 20255)

In [75]:
print(date-orders["date"])
# print((date-orders["date"]).dt.days)

0     2452 days 12:45:18.020255
1     2934 days 12:45:18.020255
2     2865 days 12:45:18.020255
3     2567 days 12:45:18.020255
4     2790 days 12:45:18.020255
                 ...
995   2880 days 12:45:18.020255
996   2821 days 12:45:18.020255
997   2669 days 12:45:18.020255
998   2734 days 12:45:18.020255
999   2508 days 12:45:18.020255
Name: date, Length: 1000, dtype: timedelta64[ns]

In [ ]:
# months passed
months = (date.year - orders["date"].dt.year) * 12 + \
    (date.month - orders["date"].dt.month)
months

0      80
1      96
2      94
3      84
4      91
       ..
995    94
996    92
997    87
998    89
999    82
Name: date, Length: 1000, dtype: int32

## Time with messages dataset

In [83]:
messages.head()

                  date                                                msg
0  2013-12-15 00:50:00                           ищу на сегодня мужика 37
1  2014-04-29 23:40:00   ПАРЕНЬ БИ ИЩЕТ ДРУГА СЕЙЧАС!! СМС ММС 0955532826
2  2012-12-30 00:21:00           Днепр.м 43 позн.с д/ж *.о  067.16.34.576
3  2014-11-28 00:31:00  КИЕВ ИЩУ Д/Ж ДО 45 МНЕ СЕЙЧАС СКУЧНО 093 629 9...
4  2013-10-26 23:11:00    Зая я тебя никогда не обижу  люблю тебя!)  Даше

In [86]:
messages["date"]=pd.to_datetime(messages["date"])
messages.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   date    1000 non-null   datetime64[ns]
 1   msg     1000 non-null   object
dtypes: datetime64[ns](1), object(1)
memory usage: 15.8+ KB

In [ ]:
# hour
messages["hour"]=messages["date"].dt.hour

# minutes
messages["minute"]=messages["date"].dt.minute

# seconds
messages["seconds"]=messages["date"].dt.second

In [90]:
messages.head()

,date,msg,hour,minute,seconds
0,2013-12-15 00:50:00,ищу на сегодня мужика 37,0,50,0
1,2014-04-29 23:40:00,ПАРЕНЬ БИ ИЩЕТ ДРУГА СЕЙЧАС!! СМС ММС 0955532826,23,40,0
2,2012-12-30 00:21:00,Днепр.м 43 позн.с д/ж *.о 067.16.34.576,0,21,0
3,2014-11-28 00:31:00,КИЕВ ИЩУ Д/Ж ДО 45 МНЕ СЕЙЧАС СКУЧНО 093 629 9...,0,31,0
4,2013-10-26 23:11:00,Зая я тебя никогда не обижу люблю тебя!) Даше,23,11,0